<html>
	<head>
        <style>
            html, body {
                max-width: 100%;
                overflow-x: hidden;
            }
        </style>
	</head>
	<body>

    <h1> <p class="western" align="justify"><span><strong><sub><span style="font-family: Times, serif;"><u>Pol&iacute;tica de Privacidade</u></span></sub></strong></span></p></h1>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Rubik, serif;">A presente pol&iacute;tica de privacidade (&ldquo;Pol&iacute;tica de Privacidade&rdquo;) tem por finalidade prestar informa&ccedil;&otilde;es sobre a coleta, uso, armazenamento, prote&ccedil;&atilde;o, compartilhamento e direitos dos usu&aacute;rios do Aplicativo (&ldquo;Usu&aacute;rios&rdquo;) em rela&ccedil;&atilde;o a seus dados pessoais (&ldquo;Informa&ccedil;&otilde;es Pessoais&rdquo;) quando da utiliza&ccedil;&atilde;o das funcionalidades do APLICATIVO.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Rubik, serif;">O ACESSO AO APLICATIVO, CADASTRO E UTILIZA&Ccedil;&Atilde;O IMPLICAM NA ACEITA&Ccedil;&Atilde;O TOTAL DOS TERMOS DESTA POL&Iacute;TICA DE PRIVACIDADE.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Rubik, serif;">CASO VOC&Ecirc; N&Atilde;O CONCORDE COM ALGUMA DISPOSI&Ccedil;&Atilde;O AQUI PRESENTE, N&Atilde;O UTILIZE OS SERVI&Ccedil;OS.</span></span></p>
    <p class="western" align="justify"><span style="font-family: Times, serif;"><u>1 &ndash; COMO COLETAMOS INFORMA&Ccedil;&Otilde;ES PESSOAIS</u></span></p>
    <p class="western" align="justify">&nbsp;</p>
    <p class="western" align="justify"><span style="font-family: Times, serif;">Podemos usar as informa&ccedil;&otilde;es que coletamos de voc&ecirc; quando voc&ecirc; se registra, faz cadastro de uma venda, solicita ou recebe pontos oriundos de vendas, trocas pontos por benef&iacute;cios, responde a uma pesquisa ou comunica&ccedil;&atilde;o de marketing, navega no </span><span style="color: #000000;"><span style="font-family: Times, serif;">Aplicativo</span></span><span style="font-family: Times, serif;"> ou usa outros recursos do </span><span style="color: #000000;"><span style="font-family: Times, serif;">Aplicativo</span></span><span style="font-family: Times, serif;">.</span></p>
    <p class="western" align="justify">&nbsp;</p>
    <ul>
        <li>
            <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">(i)&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>Informa&ccedil;&otilde;es de Cadastro:</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;s&atilde;o dados oferecidos voluntariamente pelos Usu&aacute;rios no momento do cadastro, como: nome, endere&ccedil;o de correio eletr&ocirc;nico, nome da empresa, telefone de contato, entre outros. O Usu&aacute;rio tem direito de acessar, modificar, corrigir os dados por ele fornecidos. Caso o Usu&aacute;rio atualize qualquer Informa&ccedil;&atilde;o Pessoal, o Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">poder&aacute; manter uma c&oacute;pia das informa&ccedil;&otilde;es anteriores fornecidas por ele em seus arquivos.</span></span></p>
        </li>
    </ul>
    <p class="western" align="justify"><br /><br /></p>
    <ul>
        <li>
            <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">(ii)&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>Informa&ccedil;&otilde;es de Acesso:</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;s&atilde;o dados sobre a navega&ccedil;&atilde;o dos Usu&aacute;rios e sobre o uso feito por estes do Aplicativo, que s&atilde;o coletados automaticamente por meio de tecnologias pr&oacute;prias. Podem ser coletados dados sobre as p&aacute;ginas que os Usu&aacute;rios acessam ou visitam; o dispositivo de acesso do Usu&aacute;rio, como, por exemplo, o sistema operacional; tipo de hardware; endere&ccedil;o MAC (media access control), IMEI (international mobile equipment identity) e UDID (identifier number, utilizado em dispositivos fabricados pela Apple Inc.); endere&ccedil;o de protocolo de Internet (IP); hor&aacute;rio de acesso do Usu&aacute;rio; e informa&ccedil;&otilde;es sobre os h&aacute;bitos de utiliza&ccedil;&atilde;o da Internet e prefer&ecirc;ncias do Usu&aacute;rio.</span></span></p>
        </li>
    </ul>
    <p class="western" align="justify"><br /><br /></p>
    <ul>
        <li>
            <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">(iii)&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>Informa&ccedil;&otilde;es de Servi&ccedil;o:</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;Para utiliza&ccedil;&atilde;o dos servi&ccedil;os oferecidos por meio do Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">(os &ldquo;Servi&ccedil;os&rdquo;) &eacute; indispens&aacute;vel que o Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">seja alimentado por conte&uacute;dos espec&iacute;ficos inseridos pelo pr&oacute;prio Usu&aacute;rio, como, foto, cadastro de vendas, benef&iacute;cios solicitados, entre outros. Todos esses dados ao serem inseridos no Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">s&atilde;o criptografados de forma que n&atilde;o possu&iacute;mos qualquer acesso a seu conte&uacute;do. EM NENHUMA HIP&Oacute;TESE AS INFORMA&Ccedil;&Otilde;ES DE SERVI&Ccedil;OS SER&Atilde;O COMPARTILHADAS COM QUAISQUER TERCEIROS OU SER&Atilde;O UTILIZADAS PARA QUAISQUER FINALIDADES QUE N&Atilde;O AS PREVISTAS NESTA POL&Iacute;TICA DE PRIVACIDADE.</span></span></p>
        </li>
    </ul>
    <p class="western" align="justify"><br /><br /></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;"><u>2. COMO UTILIZAMOS AS INFORMA&Ccedil;&Otilde;ES PESSOAIS</u></span></span></p>
    <ul>
        <li>
            <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">-&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>m&eacute;tricas de acesso.</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;O Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">utiliza ferramentas pr&oacute;prias e de terceiros para obter estat&iacute;sticas e m&eacute;tricas a respeito dos perfis dos Usu&aacute;rios e sobre a forma como o Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">vem sendo utilizado. Tais dados s&atilde;o aplicados no aprimoramento das funcionalidades oferecidas pelo Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">e de seu conte&uacute;do, al&eacute;m da identifica&ccedil;&atilde;o de erros de programa&ccedil;&atilde;o que possam afetar a sua utiliza&ccedil;&atilde;o.</span></span></p>
        </li>
    </ul>
    <p class="western" align="justify"><br /><br /></p>
    <ul>
        <li>
            <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">-&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>comunica&ccedil;&otilde;es importantes.</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;As Informa&ccedil;&otilde;es de Cadastro podem ser utilizadas para que o Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">possa responder a questionamentos dos Usu&aacute;rios e enviar-lhes comunica&ccedil;&otilde;es e alertas importantes sobre o seu funcionamento, servi&ccedil;os, Termos de Uso, Pol&iacute;tica de Privacidade, bem como outros comunicados.</span></span></p>
        </li>
    </ul>
    <p class="western" align="justify"><br /><br /></p>
    <ul>
        <li>
            <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">-&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>e-mail marketing.</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;Caso seja expressamente autorizado pelo Usu&aacute;rio, poderemos enviar e-mails sobre ofertas e servi&ccedil;os oferecidos pelo Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">ou por parceiros.</span></span></p>
        </li>
    </ul>
    <p class="western" align="justify"><br /><br /></p>
    <ul>
        <li>
            <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">-&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>personaliza&ccedil;&atilde;o de an&uacute;ncios.</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;As Informa&ccedil;&otilde;es Pessoais poder&atilde;o ser utilizadas para a personaliza&ccedil;&atilde;o de an&uacute;ncios de publicidade de terceiros eventualmente exibidos no ambiente do Aplicativo, a fim de oferecer servi&ccedil;os e produtos relevantes para o Usu&aacute;rio.</span></span></p>
        </li>
    </ul>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;"><u>3. COMPARTILHAMENTO DAS INFORMA&Ccedil;&Otilde;ES PESSOAIS COM TERCEIROS</u></span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">Para a melhor frui&ccedil;&atilde;o dos Servi&ccedil;os oferecidos, &eacute; imprescind&iacute;vel que as Informa&ccedil;&otilde;es Pessoais sejam compartilhadas com as seguintes empresas parceiras:</span></span></p>
    <ul>
        <li>
            <p class="western" align="justify"><a name="_heading=h.gjdgxs"></a> <span style="color: #000000;"><span style="font-family: Times, serif;">-&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>servi&ccedil;o de hospedagem.</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;O Aplicativo encontra-se hospedados em servidores de titularidade da empresa Amazon Web Services. A pol&iacute;tica de privacidade, bem como os termos de uso do servi&ccedil;o de hospedagem oferecido podem ser acessados no site&nbsp;</span></span><a href="https://aws.amazon.com/pt/legal/?nc1=f_cc"><span style="color: #332de6;"><span style="font-family: Times, serif;"><u>https://aws.amazon.com/pt/legal/?nc1=f_cc</u></span></span></a><span style="color: #000000;"><span style="font-family: Times, serif;">.</span></span></p>
        </li>
        <li>
            <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">-&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>empresas de m&eacute;tricas de acesso.</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;O Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">utiliza as ferramentas Google Analytics para processamento e visualiza&ccedil;&atilde;o de m&eacute;tricas de acesso. Tanto a pol&iacute;tica de privacidade, como os termos de uso dessas ferramentas podem ser acessados nos sites&nbsp;</span></span><a href="https://www.google.com/intl/pt/analytics/"><span style="color: #332de6;"><span style="font-family: Times, serif;"><u>https://www.google.com/intl/pt/analytics/</u></span></span></a><span style="color: #000000;"><span style="font-family: Times, serif;">. </span></span></p>
        </li>
        <li>
            <p class="western" align="justify"><a name="_heading=h.30j0zll"></a> <span style="color: #000000;"><span style="font-family: Times, serif;">-&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>ferramentas de publicidade.</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;O Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">utiliza as ferramentas Facebook Ads, Google Adwords e LinkedIn Ads para personaliza&ccedil;&atilde;o de an&uacute;ncios de publicidade e retargeting. Para consultar a pol&iacute;tica de privacidade, bem como os termos de uso dessas ferramentas, acesse o site </span></span><a href="https://www.facebook.com/business/products/ads"><span style="color: #0000ff;"><span style="font-family: Times, serif;"><u>https://www.facebook.com/business/products/ads</u></span></span></a><span style="color: #000000;"><span style="font-family: Times, serif;">,&nbsp;</span></span><a href="https://www.google.com.br/adwords/"><span style="color: #332de6;"><span style="font-family: Times, serif;"><u>https://www.google.com.br/adwords/</u></span></span></a><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;e&nbsp;</span></span><a href="https://www.linkedin.com/legal/privacy-policy"><span style="color: #332de6;"><span style="font-family: Times, serif;"><u>https://www.linkedin.com/legal/privacy-policy</u></span></span></a><span style="color: #000000;"><span style="font-family: Times, serif;">.</span></span></p>
        </li>
        <li>
            <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">-&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>ferramentas de e-mail marketing.</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;As comunica&ccedil;&otilde;es de e-mail marketing s&atilde;o processadas atrav&eacute;s de ferramentas de titularidade de terceiros, como RD Station. Para consultar a pol&iacute;tica de privacidade, bem como os termos de uso dessa empresa terceira, acesse o site&nbsp;</span></span><a href="http://www.rdstation.com.br/home/.%3C/li%3E"><span style="color: #332de6;"><span style="font-family: Times, serif;"><u>http://www.rdstation.com.br/home/</u></span></span></a><span style="color: #000000;"><span style="font-family: Times, serif;">.</span></span></p>
        </li>
        <li>
            <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">-&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Times, serif;"><strong>ferramentas de seguran&ccedil;a.</strong></span></span><span style="color: #000000;"><span style="font-family: Times, serif;">&nbsp;Para garantir que as Informa&ccedil;&otilde;es Pessoais estar&atilde;o protegidas, o Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">utiliza ferramentas de seguran&ccedil;a como certificados digitais de titularidade da HOSTGATOR. Para saber mais, consulte o site&nbsp;</span></span><a href="https://www.hostgator.com.br/"><span style="color: #0000ff;"><span style="font-family: Times, serif;"><u>https://www.hostgator.com.br/</u></span></span></a></p>
        </li>
    </ul>
    <p class="western" align="justify"><br /><br /></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">Em nenhum caso, as empresas parceiras mencionadas nessa Pol&iacute;tica de Privacidade est&atilde;o autorizadas a utilizar suas Informa&ccedil;&otilde;es Pessoais de forma diversa do disposto acima, salvo em caso de consentimento expresso do Usu&aacute;rio.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">As Informa&ccedil;&otilde;es Pessoais dos Usu&aacute;rios tamb&eacute;m poder&atilde;o ser compartilhadas com autoridades policiais, judiciais, administrativas ou com o Minist&eacute;rio P&uacute;blico do Brasil, em caso de ordem judicial que obrigue a disponibiliza&ccedil;&atilde;o das Informa&ccedil;&otilde;es Pessoais a essas autoridades.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">A transfer&ecirc;ncia de Informa&ccedil;&otilde;es Pessoais tamb&eacute;m poder&aacute; ocorrer se o Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">for adquirido ou fundir-se com outra empresa. Neste caso, os Usu&aacute;rios ser&atilde;o previamente notificados que suas Informa&ccedil;&otilde;es Pessoais ser&atilde;o transferidas e ficar&atilde;o sujeitas a outra pol&iacute;tica de privacidade.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">Em nenhuma hip&oacute;tese as Informa&ccedil;&otilde;es Pessoais ser&atilde;o compartilhadas ou vendidas a outras organiza&ccedil;&otilde;es para fins comerciais, exceto para o fornecimento de produtos ou servi&ccedil;os solicitados pelo Usu&aacute;rio, quando houver sua permiss&atilde;o para tanto.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;"><u>4. ARMAZENAMENTO DE DADOS</u></span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">As Informa&ccedil;&otilde;es Pessoais coletadas atrav&eacute;s do Aplicativo</span></span> <span style="color: #000000;"><span style="font-family: Times, serif;">s&atilde;o armazenadas pelo per&iacute;odo de 6 (seis) meses contados da data de sua coleta. Ap&oacute;s esse prazo, as informa&ccedil;&otilde;es&nbsp;poder&atilde;o, a seu exclusivo crit&eacute;rio, serem exclu&iacute;das definitivamente de nossos servidores.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;"><u>5. CONTROLE DAS INFORMA&Ccedil;&Otilde;ES PESSOAIS</u></span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">Todas as informa&ccedil;&otilde;es coletadas s&atilde;o essenciais para a utiliza&ccedil;&atilde;o do Aplicativo. O USU&Aacute;RIO poder&aacute; negar o fornecimento de alguma informa&ccedil;&atilde;o solicitada, todavia, o n&atilde;o fornecimento de determinadas informa&ccedil;&otilde;es pode impedir que o Usu&aacute;rio utilize determinada funcionalidade do Aplicativo.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">O Usu&aacute;rio poder&aacute;, a seu crit&eacute;rio e a qualquer momento, solicitar a exclus&atilde;o de suas Informa&ccedil;&otilde;es Pessoais coletadas atrav&eacute;s do Aplicativo. Contudo, poder&atilde;o, ainda, serem armazenados os dados relativos ao IP e data e hora de acesso do referido Usu&aacute;rio pelo prazo de 6 (seis) meses contados de sua coleta ou por prazo superior (caso seja solicitado por autoridade competente), conforme obriga&ccedil;&atilde;o prevista na Lei Federal n. 12.965/2014 (&ldquo;Marco Civil da Internet&rdquo;). Ap&oacute;s o t&eacute;rmino do referido prazo, o usu&aacute;rio poder&aacute; tamb&eacute;m solicitar a exclus&atilde;o definitiva de quaisquer registros de IP e data e hora de acesso.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">O Usu&aacute;rio administrador da conta poder&aacute;, ainda, revisar, melhorar e alterar as Informa&ccedil;&otilde;es Pessoais fornecidas por meio das p&aacute;ginas de perfil ou, se desejar, encerrar a sua conta mediante pedidos direcionados aos endere&ccedil;os de e-mail de contato dispon&iacute;veis no Aplicativo.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;"><u>6. ALTERA&Ccedil;&Otilde;ES NA POL&Iacute;TICA DE PRIVACIDADE</u></span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">Estamos sempre fazendo atualiza&ccedil;&otilde;es para melhorar as funcionalidades do Aplicativo. Por esse motivo, esta Pol&iacute;tica de Privacidade poder&aacute; ser alterada, a qualquer tempo e a nosso exclusivo crit&eacute;rio, a fim de refletir os ajustes realizados no Aplicativo. No entanto, sempre que ocorrer qualquer modifica&ccedil;&atilde;o nesta Pol&iacute;tica de Privacidade, o Usu&aacute;rio ser&aacute; informado previamente. Caso o Usu&aacute;rio n&atilde;o concorde com as novas disposi&ccedil;&otilde;es da Pol&iacute;tica de Privacidade, o Usu&aacute;rio poder&aacute;, a seu exclusivo crit&eacute;rio, rejeit&aacute;-la, mas, infelizmente, isso significa que o Usu&aacute;rio n&atilde;o poder&aacute; mais ter acesso ao Aplicativo e fazer uso de suas funcionalidades. Se de qualquer maneira o Usu&aacute;rio continuar a fazer uso do Aplicativo, mesmo ap&oacute;s a altera&ccedil;&atilde;o Pol&iacute;tica de Privacidade, isso significa que o Usu&aacute;rio concorda com todas as modifica&ccedil;&otilde;es.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;"><u>7. SEGURAN&Ccedil;A DE DADOS</u></span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">N&oacute;s&nbsp;utilizamos criptografia de chaves p&uacute;blicas, atrav&eacute;s de certificados digitais, para o acesso ao Aplicativo. A senha dos Usu&aacute;rios est&aacute; cifrada na base de dados.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">Todas as Informa&ccedil;&otilde;es Pessoais est&atilde;o sujeitas a pr&aacute;ticas de seguran&ccedil;a, que incluem medidas de prote&ccedil;&atilde;o f&iacute;sica e digital e buscam prevenir que terceiros n&atilde;o autorizados tenham acesso indevido &agrave;s Informa&ccedil;&otilde;es Pessoais.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">&Eacute; DE RESPONSABILIDADE DO USU&Aacute;RIO MANTER O AMBIENTE DE SEUS DISPOSITIVOS DE ACESSO SEGURO, MEDIANTE O USO DE FERRAMENTAS PR&Oacute;PRIAS DISPON&Iacute;VEIS, TAIS COMO ANTIV&Iacute;RUS E FIREWALL, ENTRE OUTRAS, E, AINDA, UTILIZAR SOFTWARE ATUALIZADOS E EFICIENTES PARA O ACESSO AOS SERVI&Ccedil;OS. EM NENHUMA HIP&Oacute;TESE SOLICITAREMOS INFORMA&Ccedil;&Otilde;ES PESSOAIS VIA E-MAIL, ESPECIALMENTE INFORMA&Ccedil;&Otilde;ES RELATIVAS A SENHAS DE ACESSO. N&Atilde;O NOS RESPONSABILIZAMOS POR QUAISQUER COMUNICA&Ccedil;&Otilde;ES ELETR&Ocirc;NICAS FRAUDULENTAS QUE COLETEM DADOS PESSOAIS DE SEUS USU&Aacute;RIOS (PHISHING).</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;"><u>8. D&Uacute;VIDAS SOBRE A PRIVACIDADE DE DADOS</u></span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">Essa Pol&iacute;tica de Privacidade &eacute; regida pelas leis da Rep&uacute;blica Federativa do Brasil. Se o Usu&aacute;rio tiver qualquer d&uacute;vida acerca desta Pol&iacute;tica de Privacidade ou, ainda, desejar fazer qualquer solicita&ccedil;&atilde;o com rela&ccedil;&atilde;o &agrave;s Informa&ccedil;&otilde;es Pessoais ou prefer&ecirc;ncias armazenadas pelo Aplicativo, dever&aacute; entrar em contato no e-mail de disponibilizado para suporte dentro do pr&oacute;prio Aplicativo.</span></span></p>
    <p class="western" align="justify"><span style="color: #000000;"><span style="font-family: Times, serif;">Na hip&oacute;tese de conflitos relacionados a esta Pol&iacute;tica de Privacidade, fica eleito o foro da cidade de S&atilde;o Jos&eacute; dos Campos, Estado de S&atilde;o Paulo, para dirimir quaisquer quest&otilde;es decorrentes desta Pol&iacute;tica de Privacidade, com ren&uacute;ncia de qualquer outro por mais privilegiado que seja.</span></span></p>
    <p class="western" align="justify">&nbsp;</p>
	</body>
</html>
