<html>
	<head>
        <head>
            <style>
                html, body {
                    max-width: 100%;
                    overflow-x: hidden;
                }
            </style>
        </head>
	</head>
	<body>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 14pt 0pt; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">O APLICATIVO e todo o seu conte&uacute;do &eacute; operado pela&nbsp;</span><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">KITOPLASTIC IND&Uacute;STRIA E COM&Eacute;RCIO DE PL&Aacute;STICO LTDA</span></strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, pessoa jur&iacute;dica de direito privado com sede na Avenida Lasar Segall, 51, Vila Celeste, S&atilde;o Paulo, Estado de S&atilde;o Paulo, devidamente inscrita no CNPJ/MF sob o n&deg; 10.628.798/0001-74 doravante denominada apenas&nbsp;&ldquo;</span><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">ADMINISTRADOR</span></strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&rdquo;.</span></p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Estes Termos de Uso cont&ecirc;m os termos e condi&ccedil;&otilde;es para a utiliza&ccedil;&atilde;o da plataforma de software operada e disponibilizada pelo&nbsp;Administrador, que oferece a profissionais e empresas sistemas que viabilizam a gest&atilde;o de campanhas de vendas atrav&eacute;s da internet, doravante apenas denominado como &ldquo;Ferramenta de Gest&atilde;o&rdquo;.</span></li>
    </ol>
    <p style="line-height: 1.7999999999999998; text-indent: -36pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 36pt; margin: 0pt -28.7pt 0pt -46.35pt;">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Estes Termos de Uso s&atilde;o v&aacute;lidos para quaisquer informa&ccedil;&otilde;es, textos, imagens e outros materiais, ou seja, quaisquer conte&uacute;dos que sejam inseridos (upload), baixados (download) ou que estejam ligados aos Servi&ccedil;os oferecidos pelo Administrador da plataforma.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Para fins destas Cl&aacute;usulas Gerais, entende-se como:</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: -36pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 36pt; margin: 0pt -28.7pt 0pt -46.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">-&nbsp;</span><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">PLATAFORMA</span></strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">:&nbsp;S&atilde;o softwares de gest&atilde;o de campanha de vendas pela internet, acessado via internet, e vinculados a um ambiente virtual, que agrega m&oacute;dulos de gest&atilde;o de cadastro de clientes, gest&atilde;o do cat&aacute;logo de produtos, gest&atilde;o de vendas, e gest&atilde;o de conte&uacute;do, elaborados em diferentes vers&otilde;es, e fornecem estrutura de instrumentos e de equipamentos necess&aacute;rios para que a empresa Administradora da possa fazer a gest&atilde;o de campanha de vendas de parceiros e operacionalizar suas pol&iacute;ticas de benef&iacute;cios aos usu&aacute;rios. Doravante, ser&aacute; denominada simplesmente como PLATAFORMA.</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: -36pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 36pt; margin: 0pt -28.7pt 0pt -46.35pt;">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: -36pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 36pt; margin: 0pt -28.7pt 0pt -46.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">-&nbsp;</span><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">APLICATIVO DE GEST&Atilde;O</span></strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">:&nbsp;&eacute; um ambiente virtual dispon&iacute;vel na internet onde o USU&Aacute;RIO, executar&aacute; e registrar&aacute; a vendas de produtos, gerando benef&iacute;cios conforme regras de bonifica&ccedil;&otilde;es previamente definidas pelo Administrador, mediante opera&ccedil;&otilde;es de registro de venda atrav&eacute;s do aplicativo e processadas pela plataforma e de demais softwares intermediadores da opera&ccedil;&atilde;o de gest&atilde;o de campanha de venda. O APLICATIVO DE GEST&Atilde;O &eacute; composto basicamente por duas estruturas: o layout da ferramenta utilizado pelo USU&Aacute;RIO e a plataforma de gest&atilde;o para as campanhas de venda que ser&atilde;o utilizadas pelo Administrador;</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: -36pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 36pt; margin: 0pt -28.7pt 0pt -46.35pt;">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: -36pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 36pt; margin: 0pt -28.7pt 0pt -46.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">-&nbsp;</span><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">LAYOUT</span></strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">:&nbsp;imagem(s) e/ou esbo&ccedil;o gr&aacute;fico que demonstra a distribui&ccedil;&atilde;o f&iacute;sica, tamanho, conceito visual, conte&uacute;do e demais caracter&iacute;sticas dos elementos gr&aacute;ficos que comp&otilde;em um ambiente virtual dispon&iacute;vel na internet, podendo tamb&eacute;m possuir aplica&ccedil;&atilde;o de imagens animadas;</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: -36pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 36pt; margin: 0pt -28.7pt 0pt -46.35pt;">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: -36pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 36pt; margin: 0pt -28.7pt 0pt -46.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">-&nbsp;</span><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">TRANSA&Ccedil;&Otilde;ES DE VENDAS</span></strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">:&nbsp;opera&ccedil;&otilde;es de cadastro de venda realizadas pelo USU&Aacute;RIO capaz de gerar os benef&iacute;cios oferecidos pela campanha de venda conforme regras previamente definidas pelo ADMINISTRADOR;</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: -34.65pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 34.65pt; margin: 0pt -28.7pt 0pt -45pt;">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: -35pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 35pt; margin: 0pt -29pt 0pt -45pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: #ffffff; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">-</span> <strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">TRANSA&Ccedil;&Otilde;ES DE RESGATE: </span></strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Opera&ccedil;&otilde;es de resgate dos pontos realizada pelos USU&Aacute;RIOS que ser&atilde;o, necessariamente, trocados por cart&otilde;es presentes ofertados pelos parceiros dentro do aplicativo e que estejam dispon&iacute;veis no momento da contrata&ccedil;&atilde;o.</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: -34.65pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 34.65pt; margin: 0pt -28.7pt 0pt -45pt;">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: -36pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 36pt; margin: 0pt -28.7pt 14pt -46.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">-&nbsp;</span><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">GATEWAY DE BENEF&Iacute;CIOS</span></strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">:&nbsp;Plataforma, aplicativo ou link de terceiros, disponibilizada pelo ADMINISTRADOR ao USU&Aacute;RIO, para viabilizar as opera&ccedil;&otilde;es de troca dos benef&iacute;cios acumulados em decorr&ecirc;ncia das campanhas disponibilizadas pelo ADMINISTRADOR ao USU&Aacute;RIO.</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 14pt 0pt; margin: 0pt -28.7pt 0pt -28.35pt;"><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">4 - A ACEITA&Ccedil;&Atilde;O DESTES TERMOS DE USO &Eacute; INDISPENS&Aacute;VEL &Agrave; UTILIZA&Ccedil;&Atilde;O DO APLICATIVO E DOS SERVI&Ccedil;OS OFERECIDOS PELA PLATAFORMA. TODOS OS USU&Aacute;RIOS DEVER&Atilde;O LER ESTES TERMOS DE USO, ENTENDE-LOS E ACEIT&Aacute;-LOS. A UTILIZA&Ccedil;&Atilde;O DO APLICATIVOS E DA PLATAFORMA IMPLICA NA ACEITA&Ccedil;&Atilde;O TOTAL DESTES TERMOS DE USO. CASO VOC&Ecirc; N&Atilde;O CONCORDE COM ALGUMA DISPOSI&Ccedil;&Atilde;O AQUI PRESENTE, N&Atilde;O UTILIZE O APLICATIVO E A PLATAFORMA OU CONTRATE OS SERVI&Ccedil;OS.</span></strong></p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- A aceita&ccedil;&atilde;o destes Termos de Uso implica na aceita&ccedil;&atilde;o da Pol&iacute;tica de Privacidade, parte integrante e indissoci&aacute;vel destes Termos de Uso, que trata da coleta, uso, armazenamento, tratamento, seguran&ccedil;a e controle das informa&ccedil;&otilde;es pessoais dos usu&aacute;rios, e pode ser encontrada no link "Termos de Uso e Pol&iacute;tica de Privacidade" dentro do APLICATIVO.</span></li>
    </ol>
    <p style="line-height: 1.7999999999999998; text-indent: -35.99999999999999pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 35.99999999999999pt; margin: 0pt -28.7pt 0pt -64.35pt;">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Caso o ADMINISTRADOR&nbsp;detecte alguma conta feita a partir de informa&ccedil;&otilde;es falsas ou por empresas irregulares ou inexistentes, essa conta ser&aacute; automaticamente deletada e estes Termos de Uso ser&atilde;o automaticamente rescindidos.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Os Servi&ccedil;os s&atilde;o oferecidos por meio do APLICATIVO/PLATAFORMA, a qual ser&aacute; disponibilizada pelo ADMINISTRADOR ao USU&Aacute;RIO por meio de download em local pr&oacute;prio, a depender da marca e tipo de aparelho m&oacute;vel utilizado pelo usu&aacute;rio. As funcionalidades dispon&iacute;veis ao Usu&aacute;rio por meio do APLICATIVO variam de acordo com as regras e pol&iacute;ticas da campanha criada pelo ADMINISTRADOR da plataforma e podem envolver:</span></li>
    </ol>
    <ul style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- centraliza&ccedil;&atilde;o do cadastro de clientes por meio de armazenamento em nuvem, podendo ser consultado por qualquer Usu&aacute;rio Cadastrado;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- acompanhamento do trabalho de todos os Usu&aacute;rios Cadastrados pelo Usu&aacute;rio Administrador;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- centraliza&ccedil;&atilde;o e organiza&ccedil;&atilde;o de hist&oacute;ricos de clientes;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- ferramenta para cria&ccedil;&atilde;o e controle de vendas; e</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- ferramenta para an&aacute;lise de desempenho de vendedores e representantes.</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- m&oacute;dulos de gest&atilde;o de cadastro de clientes</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- gest&atilde;o do cat&aacute;logo de produtos,</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">- gest&atilde;o de pontos eleg&iacute;veis para troca por benef&iacute;cios,</span></li>
    </ul>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Termos e condi&ccedil;&otilde;es adicionais podem reger o uso do Aplicativo. Neste caso, os termos e condi&ccedil;&otilde;es adicionais do Aplicativo s&atilde;o incorporados a estes Termos de Uso por refer&ecirc;ncia e vinculam os Usu&aacute;rios.&nbsp;</span></li>
    </ol>
    <p style="line-height: 1.7999999999999998; text-indent: -35.99999999999999pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 35.99999999999999pt; margin: 0pt -28.7pt 0pt -64.35pt;">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">O uso dos Servi&ccedil;os por meio do Aplicativo pode implicar na exibi&ccedil;&atilde;o de &iacute;cones e dados no dispositivo m&oacute;vel, cujo conte&uacute;do pode ser atualizado periodicamente pela Internet e/ou sistema de comunica&ccedil;&otilde;es. O Usu&aacute;rio &eacute; respons&aacute;vel por todos e quaisquer encargos cobrados pela operadora de telefonia m&oacute;vel para conex&atilde;o do Aplicativo na Internet para o correspondente uso do Servi&ccedil;o pelo Usu&aacute;rio. Baixar, instalar ou utilizar determinados aplicativos pode ser proibido ou restrito pela operadora de telefonia m&oacute;vel do Usu&aacute;rio ou pode ser tecnicamente limitado pelo pr&oacute;prio dispositivo m&oacute;vel, de forma que as funcionalidades da Plataforma inseridas no Aplicativo podem n&atilde;o funcionar em alguns dispositivos m&oacute;veis ou operadoras de telefonia celular.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Para o regular funcionamento do APLICATIVO, o USU&Aacute;RIO dever&aacute; utilizar dispositivos mobiles compat&iacute;veis com a tecnologia utilizada pelo APLICATIVO e pela PLATAFORMA, se necess&aacute;rio, sendo que eventuais problemas na sua utiliza&ccedil;&atilde;o, decorrentes de incompatibilidade sist&ecirc;mica e de tecnologias, ser&atilde;o de exclusiva responsabilidade do USU&Aacute;RIO, que dever&aacute; se adequar aos requisitos necess&aacute;rios e exigidos para o correto ao uso e funcionamento do APLICATIVO.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;O funcionamento regular do APLICATIVO e da PLATAFORMA estar&aacute; condicionado impreterivelmente &agrave; exist&ecirc;ncia de compatibilidade tecnol&oacute;gica dos suportes (hardware) do USU&Aacute;RIO, no tocante aos requisitos m&iacute;nimos necess&aacute;rios para funcionamento dos softwares.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Fica desde j&aacute; estabelecido que a presente licen&ccedil;a, bem como todos os direitos e deveres ajustados entre as partes, se estende &agrave;s melhorias funcionais e de seguran&ccedil;a que, gratuitamente e periodicamente, venham a ser disponibilizados pela ADMINISTRADOR.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;O USU&Aacute;RIO reconhece que todos os direitos relativos ao APLICATIVO e a PLATAFORMA s&atilde;o de propriedade intelectual dos seus desenvolvedores, n&atilde;o sendo permitida a revenda, subloca&ccedil;&atilde;o, divulga&ccedil;&atilde;o ou reprodu&ccedil;&atilde;o total ou parcial, transfer&ecirc;ncia ou altera&ccedil;&atilde;o de qualquer dos seus aspectos t&eacute;cnicos.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Este contrato n&atilde;o concede ao USU&Aacute;RIO qualquer direito de propriedade intelectual sobre o APLICATIVO e/ou sobre a PLATAFORMA, ou mesmo pelas suas melhorias funcionais, considerada como um todo ou apenas parte do software; e tamb&eacute;m n&atilde;o concede qualquer direito ao USU&Aacute;RIO de usar as marcas registradas do ADMINISTRADOR, seus logotipos, nomes de dom&iacute;nio ou outros recursos relativos &agrave; marca, salvo quando devidamente autorizadas por quem de direito.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: -35.99999999999999pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 35.99999999999999pt; margin: 0pt -28.7pt 0pt -64.35pt;"><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">CADASTRO</span></strong></p>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Para a contrata&ccedil;&atilde;o dos Servi&ccedil;os &eacute; necess&aacute;rio que o Usu&aacute;rio realize um cadastro pr&eacute;vio onde forne&ccedil;a voluntariamente informa&ccedil;&otilde;es sobre si, tais como: nome, sobrenome, e-mail, login, senha, documento de identidade, cadastro de pessoa f&iacute;sica (CPF), nome da empresa o qual faz parte, cadastro nacional da pessoa jur&iacute;dica (CNPJ), telefone fixo, celular, data de nascimento, endere&ccedil;o e outras informa&ccedil;&otilde;es necess&aacute;rias</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">O Usu&aacute;rio declara que as Informa&ccedil;&otilde;es Pessoais fornecidas s&atilde;o fi&eacute;is e verdadeiras e compromete-se a manter seus dados sempre atualizados. O&nbsp;ADMINISTRADOR&nbsp;n&atilde;o &eacute; respons&aacute;vel pelas informa&ccedil;&otilde;es prestadas, mas se reserva o direito de verificar, a qualquer momento, a veracidade de tais informa&ccedil;&otilde;es e solicitar, a seu exclusivo crit&eacute;rio, a documenta&ccedil;&atilde;o suporte que julgar necess&aacute;ria para a devida comprova&ccedil;&atilde;o das informa&ccedil;&otilde;es prestadas.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Caso o ADMINISTRADOR detecte alguma conta feita a partir de informa&ccedil;&otilde;es falsas, o cadastro do Usu&aacute;rio ser&aacute; automaticamente cancelado de forma que o Usu&aacute;rio n&atilde;o mais ter&aacute; acesso ao uso do APLICATIVO e a qualquer Servi&ccedil;o, n&atilde;o assistindo ao Usu&aacute;rio, por esse motivo, qualquer sorte de indeniza&ccedil;&atilde;o ou ressarcimento.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;A conta &eacute; pessoal e poder&aacute; ser acessada unicamente mediante a utiliza&ccedil;&atilde;o do login e senha criados pelo pr&oacute;prio Usu&aacute;rio no momento do cadastro, sendo o &uacute;nico e exclusivo respons&aacute;vel por manter o sigilo de seu login e senha, a fim de garantir a seguran&ccedil;a de sua conta e impedir o acesso n&atilde;o autorizado por terceiros.&nbsp;</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">O Usu&aacute;rio &eacute; o &uacute;nico respons&aacute;vel por todas as atividades associadas a sua conta. Em caso de perda, extravio ou suspeita de utiliza&ccedil;&atilde;o indevida de sua conta, login ou senha, o ADMINISTRADOR dever&aacute; ser imediatamente comunicado para que sejam tomadas as medidas cab&iacute;veis. Caso seja verificada a duplicidade de contas, o ADMINISTRADOR poder&aacute; inabilitar de forma definitiva todos os cadastros duplicados, independentemente de qualquer notifica&ccedil;&atilde;o pr&eacute;via.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: -35.99999999999999pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 35.99999999999999pt; margin: 0pt -28.7pt 0pt -64.35pt;"><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">DAS RESPONSABILIDADES</span></strong></p>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">O&nbsp;ADMINISTRADOR garante que, ressalvadas as hip&oacute;teses previstas nestes Termos de Uso, a Plataforma funcionar&aacute; 24 (vinte e quatro) horas por dia, 7 (sete) dias por semana, inclusive feriados, devendo apresentar plenas condi&ccedil;&otilde;es de acesso e funcionamento. Em caso de constata&ccedil;&atilde;o de falhas na utiliza&ccedil;&atilde;o da Plataforma ou dificuldades de acesso, a central de suporte do&nbsp;ADMINISTRADOR dever&aacute; ser comunicada, por meio do telefone (</span><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Telefone</span></strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">) ou do e-mail (</span><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">e-mail de suporte</span></strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">). A Central de Suporte estar&aacute; dispon&iacute;vel em dias &uacute;teis e no hor&aacute;rio comercial.</span></li>
    </ol>
    <p style="line-height: 1.7999999999999998; text-indent: -35.99999999999999pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 35.99999999999999pt; margin: 0pt -28.7pt 0pt -64.35pt;">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;O ADMINISTRADOR reserva-se o direito de modificar, suspender ou descontinuar temporariamente as funcionalidades disponibilizadas no APLICATIVO e na PLATAFORMA para realizar a manuten&ccedil;&atilde;o, atualiza&ccedil;&atilde;o e ajustes das configura&ccedil;&otilde;es necess&aacute;rias ao correto funcionamento.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">O&nbsp;ADMINISTRADOR n&atilde;o ser&aacute; respons&aacute;vel, sob quaisquer circunst&acirc;ncias, por eventuais perdas e danos, incluindo lucros cessantes, relacionados &agrave; suspens&atilde;o do acesso ao APLICATIVO.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;O&nbsp;ADMINISTRADOR utiliza servi&ccedil;os de terceiros para manter o APLICATIVO e a PLATAFORMA em funcionamento. Eventuais falhas que decorram do mal funcionamento de tais servi&ccedil;os, n&atilde;o ser&atilde;o de responsabilidade do ADMINISTRADOR, n&atilde;o gerando ao USU&Aacute;RIO quaisquer direitos ao ressarcimento de perdas e danos decorrentes de falha dos servi&ccedil;os destes terceiros.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;O&nbsp;ADMINISTRADOR n&atilde;o se responsabiliza pelas falhas de acesso da Plataforma decorrentes de circunst&acirc;ncias alheias &agrave; sua vontade e controle, inclusive, sem limita&ccedil;&atilde;o, falhas na internet em geral, quedas de energia, mau funcionamento eletr&ocirc;nico e/ou f&iacute;sico de qualquer rede de telecomunica&ccedil;&otilde;es, interrup&ccedil;&otilde;es ou suspens&otilde;es de conex&atilde;o e falhas nos software e/ou hardware utilizados pelos Usu&aacute;rios, bem como paralisa&ccedil;&otilde;es programadas para manuten&ccedil;&atilde;o, atualiza&ccedil;&atilde;o e ajustes de configura&ccedil;&atilde;o do APLICATIVO ou da PLATAFORMA.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;O APLICATIVO ou a PLATAFORMA podem conter links ou liga&ccedil;&otilde;es a sites ou servi&ccedil;os de terceiros que n&atilde;o pertencem e nem s&atilde;o controlados pelo ADMINISTRADOR, de forma que o&nbsp;ADMINISTRADOR n&atilde;o assume qualquer responsabilidade pelo conte&uacute;do, precis&atilde;o, pol&iacute;ticas, pr&aacute;ticas, opini&otilde;es expressas em qualquer desses sites de terceiros ou por qualquer terceiro que o Usu&aacute;rio interaja atrav&eacute;s do APLICATIVO.&nbsp;</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">O&nbsp;USU&Aacute;RIO dever&aacute; ler os termos de uso e as pol&iacute;ticas de privacidade de cada site de terceiros ou servi&ccedil;o que venha a visitar ou utilizar em decorr&ecirc;ncia do uso do APLICATIVO.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Nenhuma funcionalidade do APLICATIVO deve ser entendida como aconselhamento ou consultoria a respeito das atividades desenvolvidas pelos Usu&aacute;rios. O&nbsp;ADMINISTRADOR n&atilde;o garante aos Usu&aacute;rios qualquer resultado comercial e n&atilde;o ser&aacute; respons&aacute;vel pelo desenvolvimento de seus neg&oacute;cios ou consequ&ecirc;ncias decorrentes.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;O&nbsp;ADMINISTRADOR tamb&eacute;m n&atilde;o se responsabiliza por neg&oacute;cios desfeitos ou n&atilde;o realizados, quebras de contratos ou por eventual desinteresse na formaliza&ccedil;&atilde;o de neg&oacute;cios entre os Usu&aacute;rios e seus clientes, n&atilde;o podendo ser imputado ao ADMINISTRADOR qualquer culpa na rela&ccedil;&atilde;o comercial dos usu&aacute;rios com seus clientes.</span></li>
    </ol>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: -35.99999999999999pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 35.99999999999999pt; margin: 0pt -28.7pt 0pt -64.35pt;">&nbsp;</p>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: -35.99999999999999pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 35.99999999999999pt; margin: 0pt -28.7pt 0pt -64.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">RESPONSABILIDADE DO USU&Aacute;RIO</span></p>
    <p class="western" align="justify">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">O Usu&aacute;rio declara e garante que todos os conte&uacute;dos inseridos por ele na Plataforma:</span></li>
    </ol>
    <p style="line-height: 1.7999999999999998; margin-right: -28.65pt; text-indent: -7.65pt; text-align: justify; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 0pt 7.65pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(i) n&atilde;o violam a legisla&ccedil;&atilde;o brasileira, os dispositivos destes Termos de Uso e demais normas aplic&aacute;veis;</span></p>
    <p style="line-height: 1.7999999999999998; margin-right: -28.65pt; text-indent: -7.65pt; text-align: justify; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 0pt 7.65pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(ii) n&atilde;o infringem, nem infringir&atilde;o, qualquer obriga&ccedil;&atilde;o ou direito de quaisquer terceiros, seja pessoa natural ou entidade, incluindo, sem limita&ccedil;&atilde;o, direitos de propriedade intelectual, direitos autorais, direitos de imagem, privacidade, direitos do consumidor, entre outros; e</span></p>
    <p style="line-height: 1.7999999999999998; margin-right: -28.65pt; text-indent: -7.65pt; text-align: justify; background-color: #ffffff; margin-top: 0pt; margin-bottom: 0pt; padding: 0pt 0pt 0pt 7.65pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(iii) n&atilde;o s&atilde;o ilegais, racistas, amea&ccedil;ador, obsceno, pornogr&aacute;ficos ou violentos e nem incitam &agrave; viol&ecirc;ncia, tampouco atingem a honra de terceiro, e n&atilde;o s&atilde;o injuriosos, caluniosos ou difamantes, entre outros.</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: -35.99999999999999pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 35.99999999999999pt; margin: 0pt -28.7pt 0pt -64.35pt;">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Qualquer dano causado pelo Usu&aacute;rio ao ADMINISTRADOR ou a terceiros em virtude do n&atilde;o cumprimento das obriga&ccedil;&otilde;es aqui dispostas ou da n&atilde;o veracidade das garantiras aqui declaradas ser&aacute; reparado exclusivamente pelo Usu&aacute;rio causador do dano, n&atilde;o havendo que se falar em subsidiariedade da obriga&ccedil;&atilde;o, tampouco em solidariedade da&nbsp;ADMINISTRADOR.</span></li>
    </ol>
    <p style="line-height: 1.7999999999999998; text-indent: -35.99999999999999pt; text-align: justify; background-color: #ffffff; padding: 0pt 0pt 0pt 35.99999999999999pt; margin: 0pt -28.7pt 0pt -64.35pt;">&nbsp;</p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;S&atilde;o responsabilidades do Usu&aacute;rio, n&atilde;o se limitando &agrave;s seguintes:</span></li>
    </ol>
    <ul style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(i) utilizar o aplicativo de forma adequada e diligente, em conformidade com os presentes Termos de Uso, com a lei, a moral, os bons costumes e a ordem p&uacute;blica;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(ii) manter o ambiente de seus dispositivos de acesso ao aplicativo seguro, valendo-se de ferramentas espec&iacute;ficas para tanto, tais como antiv&iacute;rus, firewall, entre outras, de modo a contribuir para a preven&ccedil;&atilde;o de riscos eletr&ocirc;nicos;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(iii) utilizar sistemas operacionais atualizados e eficientes para a plena utiliza&ccedil;&atilde;o do APLICATIVO;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(iv) equipar-se e responsabilizar-se pelos dispositivos de hardware necess&aacute;rios para o acesso ao APLICATIVO, bem como pelo acesso desses &agrave; Internet;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(v) n&atilde;o explorar maliciosamente a seguran&ccedil;a do APLICATIVO para a pr&aacute;tica de atos il&iacute;citos, proibidos pela lei e pelos presentes Termos de Uso, lesivos aos direitos e interesses de terceiros, ou que, de qualquer forma, possa danificar, inutilizar, sobrecarregar ou deteriorar o APLICATIVO e a PLATAFORMA, bem como os documentos, arquivos e todo conte&uacute;do armazenado em seus dispositivos ou impedir a normal utiliza&ccedil;&atilde;o APLICATIVO, da PLATAFORMA e dos SERVI&Ccedil;OS;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(vi) manter c&oacute;pia de todo conte&uacute;do e dos dados que julgue importante, tendo em vista que o APLICATIVO e a PLATAFORMA poder&atilde;o passar por per&iacute;odos de manuten&ccedil;&atilde;o, indisponibilidade ou mesmo eventuais perdas de dados;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(vii) garantir a veracidade, qualidade, integridade e legalidade de seus dados e do meio atrav&eacute;s do qual adquiriu os seus dados.</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(viii) agir de forma a coibir o acesso n&atilde;o autorizado &agrave; utiliza&ccedil;&atilde;o dos Servi&ccedil;os e notificar o&nbsp;ADMINISTRADOR imediatamente de qualquer acesso n&atilde;o autorizado ou uso;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(ix) n&atilde;o vender, revender, alugar ou arrendar o Servi&ccedil;o;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(x) promover a troca dos pontos acumulados em decorr&ecirc;ncia das vendas realizadas diretamente no APLICATIVO;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">(xi) verificar se o conte&uacute;do e o benef&iacute;cio que busca adquirir com os pontos acumulados est&atilde;o dispon&iacute;veis no momento do resgate. A oferta de benef&iacute;cio no aplicativo n&atilde;o garante ao usu&aacute;rio o direito na troca, devendo o produto ou oferta estar dispon&iacute;vel no momento do resgate dos pontos.&nbsp;</span></li>
    </ul>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">32 - O ADMINISTRADOR n&atilde;o se responsabiliza pela defici&ecirc;ncia no funcionamento adequado do APLICATIVO ou PLATAFORMA que porventura seja ocasionado:</span></p>
    <ol style="margin-top: 0pt; margin-bottom: 0pt;">
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Em decorr&ecirc;ncia de ato exclusivo do USU&Aacute;RIO, de terceiros ou de comprovada falha dos softwares, ou ainda nos casos de for&ccedil;a maior.</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Falhas nos sistemas de transmiss&atilde;o ou de roteamento de dados via Internet entre os provedores de servi&ccedil;os necess&aacute;rios para disponibiliza&ccedil;&atilde;o do APLICATIVO e da PLATAFORMA;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Pelo inadequado funcionamento do APLICATIVO em virtude de incompatibilidades com o hardware e/ou software utilizado pelo USU&Aacute;RIO;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Por defici&ecirc;ncia ou m&aacute; informa&ccedil;&atilde;o ou conte&uacute;do acrescidos pelo USU&Aacute;RIO no APLICATIVO;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Por defici&ecirc;ncia de funcionamento, ou mesmo por incompatibilidade t&eacute;cnica, do Gateway de Benef&iacute;cios escolhido pelo USU&Aacute;RIO para realizar o resgate dos pontos acumulados em decorr&ecirc;ncia das vendas realizadas.&nbsp;</span></li>
        <li><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">De igual forma, o ADMINISTRADOR n&atilde;o ser&aacute; respons&aacute;vel por opera&ccedil;&atilde;o de venda n&atilde;o conclu&iacute;da no APLICATIVO em decorr&ecirc;ncia do n&atilde;o funcionamento, defeito, ou mesmo uso inadequado, do Gateway de Benef&iacute;cio.</span></li>
    </ol>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 14pt -28.7pt 14pt -28.35pt;"><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">DOS BENEF&Iacute;CIOS DA CAMPANHA DE VENDAS</span></strong></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">33.- O APLICATIVO disponibilizado pelo ADMINISTRADOR visa proporcionar ao USU&Aacute;RIO o ac&uacute;mulo de pontos atrelado &agrave;s opera&ccedil;&otilde;es de venda de produtos, os quais ser&atilde;o, a crit&eacute;rio da campanha de vendas criada pelo ADMINISTRADOR, trocadas por produtos oferecidos por parceiros no APLICATIVO.</span></p>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">34 - O USU&Aacute;RIO ser&aacute; bonificado com pontos dentro do APLICATIVO conforme ocorram as vendas de produtos definidos pelo ADMINISTRADOR. Os pontos ser&atilde;o contabilizados nas respectivas contas dos USU&Aacute;RIOS atrav&eacute;s do registro da venda por meio da leitura de c&oacute;digos de identifica&ccedil;&atilde;o do produto.</span></p>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">35 &ndash; Somente os produtos cadastrados e disponibilizados pelo ADMINISTRADOR ap&oacute;s o in&iacute;cio do uso do APLICATIVO e da PLATAFORMA ser&atilde;o pass&iacute;veis de gerar a bonifica&ccedil;&atilde;o em decorr&ecirc;ncia da venda. Produtos que j&aacute; estiverem em estoque n&atilde;o gerar&atilde;o qualquer tipo de benef&iacute;cio, ainda que de mesmo tipo, g&ecirc;nero, modelo e quantidade.</span></p>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">36 -&nbsp; Os produtos ofertados pelos parceiros para a troca dos pontos no APLICATIVO n&atilde;o s&atilde;o vinculantes entre as partes e somente geram direito ao USU&Aacute;RIO pela troca se dispon&iacute;veis no momento da solicita&ccedil;&atilde;o de resgate e troca.</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">37 - Os USU&Aacute;RIOS ter&atilde;o o prazo de at&eacute; 30 dias para realizar o resgate dos pontos obtidos com as vendas de produtos. Ap&oacute;s este prazo, os pontos expirar&atilde;o sem direito a qualquer ressarcimento pelo ADMINISTRADOR ao USU&Aacute;RIO.</span></p>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">38 - Eventuais problemas t&eacute;cnicos ou instabilidades da PLATAFORMA ou do APLICATIVO que prejudiquem ou interfiram na arrecada&ccedil;&atilde;o, ac&uacute;mulo, troca ou outros, dos pontos obtidos com a transa&ccedil;&otilde;es de vendas, n&atilde;o s&atilde;o de responsabilidade dos ADMINISTRADORES, sendo que a reposi&ccedil;&atilde;o e repara&ccedil;&atilde;o de eventuais benef&iacute;cios obtidos ficam a crit&eacute;rio, exclusivo e discricion&aacute;rio, dos ADMINISTRADORES.</span></p>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 14pt -28.7pt 14pt -28.35pt;"><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">DO PRAZO</span></strong></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">39 - O ADMINISTRADOR poder&aacute;, a qualquer tempo e sem motivo, interromper uso do APLICATIVO e da PLATAFORMA, n&atilde;o gerando qualquer direito a indeniza&ccedil;&atilde;o ou ressarcimento ao USU&Aacute;RIO, salvo os pontos j&aacute; adquiridos e resgates j&aacute; efetuados, os quais dever&atilde;o ser garantidos pelo ADMINISTRADOR.</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">40 -&nbsp; Caso a USU&Aacute;RIO d&ecirc; ensejo &agrave; rescis&atilde;o do contrato, este perder&aacute; todo e qualquer benef&iacute;cio, seja ele de pontos ou produtos resgatados a que teria direito, sem preju&iacute;zo do ressarcimento de eventuais danos causados.</span></p>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><strong><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">DO FORO</span></strong></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">41 - As partes elegem a cidade de S&atilde;o Jos&eacute; dos Campos/SP como foro para discuss&otilde;es a respeito de toda e qualquer obriga&ccedil;&atilde;o oriunda deste contrato.</span></p>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 14pt -28.7pt 14pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">CL&Aacute;USULAS FINAIS</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">42 - Todas as comunica&ccedil;&otilde;es relativas ao presente contrato ser&atilde;o realizadas por escrito, na forma de e-mail para o endere&ccedil;o (e-mail), exce&ccedil;&atilde;o feita ao suporte t&eacute;cnico, que poder&aacute; ser prestado tamb&eacute;m por telefone, pelo ADMINISTRADOR.</span></p>
    <p class="western" align="justify">&nbsp;</p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">43 -&nbsp; Todos os direitos e obriga&ccedil;&otilde;es decorrentes da rela&ccedil;&atilde;o jur&iacute;dica entre as partes n&atilde;o poder&atilde;o ser cedidos pelo USU&Aacute;RIO, no todo ou em parte, sem o consentimento pr&eacute;vio e por escrito do ADMINISTRADOR.</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
    <p style="line-height: 1.7999999999999998; text-indent: 28.35pt; text-align: justify; margin: 0pt -28.7pt 0pt -28.35pt;"><span style="font-size: 12pt; font-family: Times,serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">44 - A declara&ccedil;&atilde;o de invalidade, ilegalidade ou inexequibilidade de qualquer cl&aacute;usula, termo ou disposi&ccedil;&atilde;o destas cl&aacute;usulas gerais n&atilde;o afetar&aacute; a validade, legalidade ou exequibilidade das demais cl&aacute;usulas, termos ou disposi&ccedil;&otilde;es do contrato, ou ainda do contrato como um todo.</span></p>
	</body>
</html>
